name: CI Workflow

on:
  push:
    branches:
      - build
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: development

    - name: Build
      run: gradle build

    - name: Test
      run: gradle RunTest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        export DOCKER_BUILDKIT=1
        docker build -t blackfriday .

    - name: Upload Docker Images to Docker Container
      run: echo "e" | docker run -it blackfriday

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: build/test-results/**/*.xml
