name: CI Workflow

on:
  push:
    branches:
      - build
      - development

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: development

    - name: Build
      run: gradle build

    - name: Test
      run: gradle RunTest

    - name: Deploy
      run: |
        docker build -t blackfriday .
        docker run -it blackfriday

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: build/test-results/**/*.xml
